name: SDK Tests

on: [push]

jobs:
  run:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer:v1

    - name: Check PHP Version
      run: php -v

    - name: Check PHP Extensions
      run: php -m

    - name: Check Composer Version
      run: composer -V

    - name: Validate composer.json and composer.lock
      run: composer validate

    # TODO: remove the following step once Mockery releases backport of https://github.com/mockery/mockery/pull/980 to v0.9.XX
    #- name: PHP v7.4 workaround
    #  run: composer require --dev hamcrest/hamcrest-php:2.0 mockery/mockery:1.3.1 --ignore-platform-reqs

    # TODO: remove --ignore-platform-reqs once Mockery releases backport of https://github.com/mockery/mockery/pull/980 to v0.9.XX
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs
    
    - name: Run test suite
      run: composer test
